version = "0.1"

[build]
target = "index.html"
dist = "dist"
# Disable lightningcss
css_processor = "none"


[serve]
# The address to serve on LAN.
address = "0.0.0.0"
# The port to serve on.
port = 8080

